basePath: /
definitions:
  entity.ErrorResponse:
    properties:
      error:
        example: Internal server error
        type: string
    type: object
  entity.Message:
    properties:
      id:
        type: integer
      message:
        type: string
      username:
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a chat microservice with WebSocket support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Chat Microservice API
  version: "1.0"
paths:
  /messages:
    get:
      description: Возвращает все сообщения из чата
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Message'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: Получить сообщения
      tags:
      - messages
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
